name: Merge all branches into master
on: push
jobs:
  merge-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git config --global user.name "zorrobert"
          git config --global user.email "robert.lotz@mailbox.org"
      - name: Fetch all branches
        run: git fetch --all
      - name: Reset master to upstream
        run: |
          echo "reset master branch to upstream"
          git checkout master
          git reset --hard upstream/master
          echo "branch master reset to upstream"
      - name: Merge branches into master
        run: |
          git checkout master
          echo "add nix-community/home-manager as upstream"
          git remote add upstream https://github.com/nix-community/home-manager.git
          echo "merge all branches"
          git branch --all | sed 's/  remotes\///g' | sed 's/\/master//g' | sed 's/\/dev//g' | sed 's/\/HEAD//g' | grep "origin/" | xargs -L1 git merge
          echo "force-push all changes to master"
          git push --force
          echo "done"
