name: Merge all branches into master
on: push
jobs:
  merge-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git config --global user.name "zorrobert"
          git config --global user.email "robert.lotz@mailbox.org"
      - name: Fetch all branches
        run: git fetch --all
      - name: Update master from upstream
        run: |
          echo "STUB: Update master from upstream"
      - name: Merge branches into master
        run: |
          git checkout master

          echo "echo info"
          BRANCHES=$(git branch --all | sed 's/  remotes\///g' | sed 's/\/master//g' | sed 's/\/dev//g' | sed 's/\/HEAD//g' | grep "origin/") 
          # | xargs -L1 git merge
          for branch in $BRANCHES; do
            echo "Merging $branch into master..."
            git merge $branch
            echo "Merged $branch into master..."
          done
          echo "echo exit"
          
